# Book Recommendation App

# Book database (you can add more books here)
books = {
    "1": {"title": "To Kill a Mockingbird", "author": "Harper Lee", "genre": "Classic"},
    "2": {"title": "The Hunger Games", "author": "Suzanne Collins", "genre": "Dystopian"},
    "3": {"title": "1984", "author": "George Orwell", "genre": "Dystopian"},
    "4": {"title": "Pride and Prejudice", "author": "Jane Austen", "genre": "Romance"},
    "5": {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "6": {"title": "The Handmaid's Tale", "author": "Margaret Atwood", "genre": "Dystopian"},
    "7": {"title": "The Nightingale", "author": "Kristin Hannah", "genre": "Historical Fiction"},
    "8": {"title": "The Hate U Give", "author": "Angie Thomas", "genre": "Young Adult"},
    "9": {"title": "The Power", "author": "Naomi Alderman", "genre": "Science Fiction"},
    "10": {"title": "The Song of Achilles", "author": "Madeline Miller", "genre": "Historical Fiction"},
    "11": {"title": "Jane Eyre", "author": "Charlotte Brontë", "genre": "Classic"},
    "12": {"title": "Little Women", "author": "Louisa May Alcott", "genre": "Classic"},
    "13": {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "genre": "Classic"},
    "14": {"title": "The Book Thief", "author": "Markus Zusak", "genre": "Historical Fiction"},
    "15": {"title": "Brave New World", "author": "Aldous Huxley", "genre": "Dystopian"},
    "16": {"title": "Moby-Dick", "author": "Herman Melville", "genre": "Classic"},
    "17": {"title": "The Road", "author": "Cormac McCarthy", "genre": "Dystopian"},
    "18": {"title": "Wuthering Heights", "author": "Emily Brontë", "genre": "Classic"},
    "19": {"title": "The Alchemist", "author": "Paulo Coelho", "genre": "Adventure"},
    "20": {"title": "The Fault in Our Stars", "author": "John Green", "genre": "Young Adult"},
    "21": {"title": "Gone Girl", "author": "Gillian Flynn", "genre": "Thriller"},
    "22": {"title": "Divergent", "author": "Veronica Roth", "genre": "Dystopian"},
    "23": {"title": "The Hobbit", "author": "J.R.R. Tolkien", "genre": "Fantasy"},
    "24": {"title": "The Girl on the Train", "author": "Paula Hawkins", "genre": "Thriller"},
    "25": {"title": "The Kite Runner", "author": "Khaled Hosseini", "genre": "Historical Fiction"},
    "26": {"title": "Fahrenheit 451", "author": "Ray Bradbury", "genre": "Dystopian"},
    "27": {"title": "Life of Pi", "author": "Yann Martel", "genre": "Adventure"},
    "28": {"title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "genre": "Fantasy"},
    "29": {"title": "The Da Vinci Code", "author": "Dan Brown", "genre": "Thriller"},
    "30": {"title": "Memoirs of a Geisha", "author": "Arthur Golden", "genre": "Historical Fiction"},
    "31": {"title": "The Secret Life of Bees", "author": "Sue Monk Kidd", "genre": "Historical Fiction"},
    "32": {"title": "The Maze Runner", "author": "James Dashner", "genre": "Dystopian"},
    "33": {"title": "The Chronicles of Narnia", "author": "C.S. Lewis", "genre": "Fantasy"},
    "34": {"title": "Ender's Game", "author": "Orson Scott Card", "genre": "Science Fiction"},
    "35": {"title": "The Lovely Bones", "author": "Alice Sebold", "genre": "Mystery"},
    "36": {"title": "The Perks of Being a Wallflower", "author": "Stephen Chbosky", "genre": "Young Adult"},
    "37": {"title": "The Lightning Thief", "author": "Rick Riordan", "genre": "Fantasy"},
    "38": {"title": "A Game of Thrones", "author": "George R.R. Martin", "genre": "Fantasy"},
    "39": {"title": "Outlander", "author": "Diana Gabaldon", "genre": "Historical Fiction"},
    "40": {"title": "The Outsiders", "author": "S.E. Hinton", "genre": "Young Adult"},
    "41": {"title": "Twilight", "author": "Stephenie Meyer", "genre": "Fantasy"},
    "42": {"title": "The Catch-22", "author": "Joseph Heller", "genre": "Classic"},
    "43": {"title": "Water for Elephants", "author": "Sara Gruen", "genre": "Historical Fiction"},
    "44": {"title": "The Giver", "author": "Lois Lowry", "genre": "Dystopian"},
    "45": {"title": "Frankenstein", "author": "Mary Shelley", "genre": "Classic"},
    "46": {"title": "The Shining", "author": "Stephen King", "genre": "Horror"},
    "47": {"title": "The Martian", "author": "Andy Weir", "genre": "Science Fiction"},
    "48": {"title": "Big Little Lies", "author": "Liane Moriarty", "genre": "Mystery"},
    "49": {"title": "The Goldfinch", "author": "Donna Tartt", "genre": "Fiction"},
    "50": {"title": "The Bell Jar", "author": "Sylvia Plath", "genre": "Classic"},
    "51": {"title": "The Poisonwood Bible", "author": "Barbara Kingsolver", "genre": "Fiction"},
    "52": {"title": "The Time Traveler's Wife", "author": "Audrey Niffenegger", "genre": "Romance"},
    "53": {"title": "The Wind-Up Bird Chronicle", "author": "Haruki Murakami", "genre": "Fiction"},
    "54": {"title": "Beloved", "author": "Toni Morrison", "genre": "Historical Fiction"},
    "55": {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "genre": "Science Fiction"},
    "56": {"title": "Dracula", "author": "Bram Stoker", "genre": "Horror"},
    "57": {"title": "A Wrinkle in Time", "author": "Madeleine L'Engle", "genre": "Fantasy"},
    "58": {"title": "The Secret Garden", "author": "Frances Hodgson Burnett", "genre": "Classic"},
    "59": {"title": "The Help", "author": "Kathryn Stockett", "genre": "Historical Fiction"},
    "60": {"title": "The Immortal Life of Henrietta Lacks", "author": "Rebecca Skloot", "genre": "Non-Fiction"},
    "61": {"title": "The Joy Luck Club", "author": "Amy Tan", "genre": "Fiction"},
    "62": {"title": "The Light Between Oceans", "author": "M.L. Stedman", "genre": "Historical Fiction"},
    "63": {"title": "The Curious Incident of the Dog in the Night-Time", "author": "Mark Haddon", "genre": "Mystery"},
    "64": {"title": "The Thirteenth Tale", "author": "Diane Setterfield", "genre": "Mystery"},
    "65": {"title": "The Shadow of the Wind", "author": "Carlos Ruiz Zafón", "genre": "Mystery"},
    "66": {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "genre": "Mystery"},
    "67": {"title": "Shutter Island", "author": "Dennis Lehane", "genre": "Thriller"},
    "68": {"title": "The Guernsey Literary and Potato Peel Pie Society", "author": "Mary Ann Shaffer & Annie Barrows", "genre": "Historical Fiction"},
    "69": {"title": "Room", "author": "Emma Donoghue", "genre": "Fiction"},
    "70": {"title": "Good Omens", "author": "Neil Gaiman & Terry Pratchett", "genre": "Fantasy"},
    "71": {"title": "The Night Circus", "author": "Erin Morgenstern", "genre": "Fantasy"},
    "72": {"title": "Cloud Atlas", "author": "David Mitchell", "genre": "Science Fiction"},
    "73": {"title": "The Art of Racing in the Rain", "author": "Garth Stein", "genre": "Fiction"},
    "74": {"title": "Where the Crawdads Sing", "author": "Delia Owens", "genre": "Mystery"},
    "75": {"title": "The Lovely War", "author": "Julie Berry", "genre": "Historical Fiction"},
    "76": {"title": "The Name of the Wind", "author": "Patrick Rothfuss", "genre": "Fantasy"},
    "77": {"title": "The Secret History", "author": "Donna Tartt", "genre": "Mystery"},
    "78": {"title": "The Night Watch", "author": "Sarah Waters", "genre": "Historical Fiction"},
    "79": {"title": "Eleanor Oliphant Is Completely Fine", "author": "Gail Honeyman", "genre": "Fiction"},
    "80": {"title": "The Book of Lost Things", "author": "John Connolly", "genre": "Fantasy"},
    "81": {"title": "Never Let Me Go", "author": "Kazuo Ishiguro", "genre": "Dystopian"},
    "82": {"title": "The Remains of the Day", "author": "Kazuo Ishiguro", "genre": "Historical Fiction"},
    "83": {"title": "The Stranger", "author": "Albert Camus", "genre": "Classic"},
    "84": {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde", "genre": "Classic"},
    "85": {"title": "Rebecca", "author": "Daphne du Maurier", "genre": "Gothic"},
    "86": {"title": "The Stand", "author": "Stephen King", "genre": "Horror"},
    "87": {"title": "The Color Purple", "author": "Alice Walker", "genre": "Historical Fiction"},
    "88": {"title": "The Shadow of the Wind", "author": "Carlos Ruiz Zafón", "genre": "Mystery"},
    "89": {"title": "The Wind-Up Bird Chronicle", "author": "Haruki Murakami", "genre": "Fiction"},
    "90": {"title": "The Road", "author": "Cormac McCarthy", "genre": "Dystopian"},
    "91": {"title": "A Tale of Two Cities", "author": "Charles Dickens", "genre": "Classic"},
    "92": {"title": "Emma", "author": "Jane Austen", "genre": "Classic"},
    "93": {"title": "Mansfield Park", "author": "Jane Austen", "genre": "Classic"},
    "94": {"title": "Persuasion", "author": "Jane Austen", "genre": "Classic"},
    "95": {"title": "Northanger Abbey", "author": "Jane Austen", "genre": "Classic"},
    "96": {"title": "Sense and Sensibility", "author": "Jane Austen", "genre": "Classic"},
    "97": {"title": "David Copperfield", "author": "Charles Dickens", "genre": "Classic"},
    "98": {"title": "Bleak House", "author": "Charles Dickens", "genre": "Classic"},
    "99": {"title": "Great Expectations", "author": "Charles Dickens", "genre": "Classic"},
    "100": {"title": "The Tale of Genji", "author": "Murasaki Shikibu", "genre": "Classic"},
    "101": {"title": "War and Peace", "author": "Leo Tolstoy", "genre": "Classic"},
    "102": {"title": "Anna Karenina", "author": "Leo Tolstoy", "genre": "Classic"},
    "103": {"title": "Madame Bovary", "author": "Gustave Flaubert", "genre": "Classic"},
    "104": {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "genre": "Classic"},
    "105": {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "genre": "Classic"},
    "106": {"title": "The Idiot", "author": "Fyodor Dostoevsky", "genre": "Classic"},
    "107": {"title": "Les Misérables", "author": "Victor Hugo", "genre": "Classic"},
    "108": {"title": "The Count of Monte Cristo", "author": "Alexandre Dumas", "genre": "Classic"},
    "109": {"title": "The Three Musketeers", "author": "Alexandre Dumas", "genre": "Classic"},
    "110": {"title": "Catch-22", "author": "Joseph Heller", "genre": "Classic"},
    "111": {"title": "One Hundred Years of Solitude", "author": "Gabriel Garcia Marquez", "genre": "Magical Realism"},
    "112": {"title": "Love in the Time of Cholera", "author": "Gabriel Garcia Marquez", "genre": "Romance"},
    "113": {"title": "Chronicle of a Death Foretold", "author": "Gabriel Garcia Marquez", "genre": "Fiction"},
    "114": {"title": "Of Mice and Men", "author": "John Steinbeck", "genre": "Classic"},
    "115": {"title": "East of Eden", "author": "John Steinbeck", "genre": "Classic"},
    "116": {"title": "The Grapes of Wrath", "author": "John Steinbeck", "genre": "Classic"},
    "117": {"title": "Cannery Row", "author": "John Steinbeck", "genre": "Classic"},
    "118": {"title": "The Pearl", "author": "John Steinbeck", "genre": "Classic"},
    "119": {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "genre": "Classic"},
    "120": {"title": "A Farewell to Arms", "author": "Ernest Hemingway", "genre": "Classic"},
    "121": {"title": "For Whom the Bell Tolls", "author": "Ernest Hemingway", "genre": "Classic"},
    "122": {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "genre": "Classic"},
    "123": {"title": "To Have and Have Not", "author": "Ernest Hemingway", "genre": "Classic"},
    "124": {"title": "The Stranger", "author": "Albert Camus", "genre": "Classic"},
    "125": {"title": "The Plague", "author": "Albert Camus", "genre": "Classic"},
    "126": {"title": "The Fall", "author": "Albert Camus", "genre": "Classic"},
    "127": {"title": "The Trial", "author": "Franz Kafka", "genre": "Classic"},
    "128": {"title": "The Castle", "author": "Franz Kafka", "genre": "Classic"},
    "129": {"title": "Metamorphosis", "author": "Franz Kafka", "genre": "Classic"},
    "130": {"title": "Don Quixote", "author": "Miguel de Cervantes", "genre": "Classic"},
    "131": {"title": "The Odyssey", "author": "Homer", "genre": "Classic"},
    "132": {"title": "The Iliad", "author": "Homer", "genre": "Classic"},
    "133": {"title": "The Aeneid", "author": "Virgil", "genre": "Classic"},
    "134": {"title": "The Divine Comedy", "author": "Dante Alighieri", "genre": "Classic"},
    "135": {"title": "Paradise Lost", "author": "John Milton", "genre": "Classic"},
    "136": {"title": "The Canterbury Tales", "author": "Geoffrey Chaucer", "genre": "Classic"},
    "137": {"title": "Gulliver's Travels", "author": "Jonathan Swift", "genre": "Classic"},
    "138": {"title": "Robinson Crusoe", "author": "Daniel Defoe", "genre": "Classic"},
    "139": {"title": "Moll Flanders", "author": "Daniel Defoe", "genre": "Classic"},
    "140": {"title": "The Adventures of Tom Sawyer", "author": "Mark Twain", "genre": "Classic"},
    "141": {"title": "The Adventures of Huckleberry Finn", "author": "Mark Twain", "genre": "Classic"},
    "142": {"title": "Treasure Island", "author": "Robert Louis Stevenson", "genre": "Classic"},
    "143": {"title": "Dr. Jekyll and Mr. Hyde", "author": "Robert Louis Stevenson", "genre": "Classic"},
    "144": {"title": "Kidnapped", "author": "Robert Louis Stevenson", "genre": "Classic"},
    "145": {"title": "The Strange Case of Dr Jekyll and Mr Hyde", "author": "Robert Louis Stevenson", "genre": "Classic"},
    "146": {"title": "The Scarlet Letter", "author": "Nathaniel Hawthorne", "genre": "Classic"},
    "147": {"title": "The House of the Seven Gables", "author": "Nathaniel Hawthorne", "genre": "Classic"},
    "148": {"title": "The Blithedale Romance", "author": "Nathaniel Hawthorne", "genre": "Classic"},
    "149": {"title": "Twice-Told Tales", "author": "Nathaniel Hawthorne", "genre": "Classic"},
    "150": {"title": "The Birthmark", "author": "Nathaniel Hawthorne", "genre": "Classic"},
    "151": {"title": "The Complete Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "152": {"title": "The Hound of the Baskervilles", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "153": {"title": "The Adventures of Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "154": {"title": "The Memoirs of Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "155": {"title": "The Return of Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "156": {"title": "The Valley of Fear", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "157": {"title": "The Sign of the Four", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "158": {"title": "A Study in Scarlet", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "159": {"title": "His Last Bow", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "160": {"title": "The Case-Book of Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Mystery"},
    "161": {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "162": {"title": "This Side of Paradise", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "163": {"title": "Tender Is the Night", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "164": {"title": "The Beautiful and Damned", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "165": {"title": "The Last Tycoon", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "166": {"title": "The Collected Stories of F. Scott Fitzgerald", "author": "F. Scott Fitzgerald", "genre": "Classic"},
    "167": {"title": "The Waste Land", "author": "T.S. Eliot", "genre": "Classic"},
    "168": {"title": "The Love Song of J. Alfred Prufrock", "author": "T.S. Eliot", "genre": "Classic"},
    "169": {"title": "Four Quartets", "author": "T.S. Eliot", "genre": "Classic"},
    "170": {"title": "The Hollow Men", "author": "T.S. Eliot", "genre": "Classic"},
    "171": {"title": "Murder in the Cathedral", "author": "T.S. Eliot", "genre": "Classic"},
    "172": {"title": "Old Possum's Book of Practical Cats", "author": "T.S. Eliot", "genre": "Classic"},
    "173": {"title": "To the Lighthouse", "author": "Virginia Woolf", "genre": "Classic"},
    "174": {"title": "Mrs Dalloway", "author": "Virginia Woolf", "genre": "Classic"},
    "175": {"title": "Orlando", "author": "Virginia Woolf", "genre": "Classic"},
    "176": {"title": "The Waves", "author": "Virginia Woolf", "genre": "Classic"},
    "177": {"title": "A Room of One's Own", "author": "Virginia Woolf", "genre": "Classic"},
    "178": {"title": "Between the Acts", "author": "Virginia Woolf", "genre": "Classic"},
    "179": {"title": "Jacob's Room", "author": "Virginia Woolf", "genre": "Classic"},
    "180": {"title": "The Death of the Moth", "author": "Virginia Woolf", "genre": "Classic"},
    "181": {"title": "As I Lay Dying", "author": "William Faulkner", "genre": "Classic"},
    "182": {"title": "The Sound and the Fury", "author": "William Faulkner", "genre": "Classic"},
    "183": {"title": "Light in August", "author": "William Faulkner", "genre": "Classic"},
    "184": {"title": "Absalom, Absalom!", "author": "William Faulkner", "genre": "Classic"},
    "185": {"title": "Go Down, Moses", "author": "William Faulkner", "genre": "Classic"},
    "186": {"title": "The Hamlet", "author": "William Faulkner", "genre": "Classic"},
    "187": {"title": "The Reivers", "author": "William Faulkner", "genre": "Classic"},
    "188": {"title": "The Wild Palms", "author": "William Faulkner", "genre": "Classic"},
    "189": {"title": "Sanctuary", "author": "William Faulkner", "genre": "Classic"},
    "190": {"title": "The Mansion", "author": "William Faulkner", "genre": "Classic"},
    "191": {"title": "Brave New World", "author": "Aldous Huxley", "genre": "Dystopian"},
    "192": {"title": "Island", "author": "Aldous Huxley", "genre": "Science Fiction"},
    "193": {"title": "The Doors of Perception", "author": "Aldous Huxley", "genre": "Non-Fiction"},
    "194": {"title": "Antic Hay", "author": "Aldous Huxley", "genre": "Fiction"},
    "195": {"title": "Crome Yellow", "author": "Aldous Huxley", "genre": "Fiction"},
    "196": {"title": "Eyeless in Gaza", "author": "Aldous Huxley", "genre": "Fiction"},
    "197": {"title": "Point Counter Point", "author": "Aldous Huxley", "genre": "Fiction"},
    "198": {"title": "After Many a Summer Dies the Swan", "author": "Aldous Huxley", "genre": "Fiction"},
    "199": {"title": "The Complete Stories", "author": "Franz Kafka", "genre": "Classic"},
    "200": {"title": "The Trial", "author": "Franz Kafka", "genre": "Classic"},
    "201": {"title": "Metamorphosis", "author": "Franz Kafka", "genre": "Classic"},
    "202": {"title": "The Castle", "author": "Franz Kafka", "genre": "Classic"},
    "203": {"title": "In the Penal Colony", "author": "Franz Kafka", "genre": "Classic"},
    "204": {"title": "The Burrow", "author": "Franz Kafka", "genre": "Classic"},
    "205": {"title": "Amerika", "author": "Franz Kafka", "genre": "Classic"},
    "206": {"title": "Meditations", "author": "Marcus Aurelius", "genre": "Philosophy"},
    "207": {"title": "The Republic", "author": "Plato", "genre": "Philosophy"},
    "208": {"title": "Nicomachean Ethics", "author": "Aristotle", "genre": "Philosophy"},
    "209": {"title": "The Prince", "author": "Niccolò Machiavelli", "genre": "Philosophy"},
    "210": {"title": "Thus Spoke Zarathustra", "author": "Friedrich Nietzsche", "genre": "Philosophy"},
    "211": {"title": "Beyond Good and Evil", "author": "Friedrich Nietzsche", "genre": "Philosophy"},
    "212": {"title": "The Communist Manifesto", "author": "Karl Marx & Friedrich Engels", "genre": "Philosophy"},
    "213": {"title": "Das Kapital", "author": "Karl Marx", "genre": "Philosophy"},
    "214": {"title": "The Wealth of Nations", "author": "Adam Smith", "genre": "Philosophy"},
    "215": {"title": "The Social Contract", "author": "Jean-Jacques Rousseau", "genre": "Philosophy"},
    "216": {"title": "Civil Disobedience", "author": "Henry David Thoreau", "genre": "Philosophy"},
    "217": {"title": "Walden", "author": "Henry David Thoreau", "genre": "Philosophy"},
    "218": {"title": "The Art of War", "author": "Sun Tzu", "genre": "Philosophy"},
    "219": {"title": "The Tao Te Ching", "author": "Laozi", "genre": "Philosophy"},
    "220": {"title": "The Analects", "author": "Confucius", "genre": "Philosophy"},
    "221": {"title": "The Republic", "author": "Plato", "genre": "Philosophy"},
    "222": {"title": "The Symposium", "author": "Plato", "genre": "Philosophy"},
    "223": {"title": "The Birth of Tragedy", "author": "Friedrich Nietzsche", "genre": "Philosophy"},
    "224": {"title": "The Critique of Pure Reason", "author": "Immanuel Kant", "genre": "Philosophy"},
    "225": {"title": "Being and Nothingness", "author": "Jean-Paul Sartre", "genre": "Philosophy"},
    "226": {"title": "The Myth of Sisyphus", "author": "Albert Camus", "genre": "Philosophy"},
    "227": {"title": "The Stranger", "author": "Albert Camus", "genre": "Classic"},
    "228": {"title": "The Plague", "author": "Albert Camus", "genre": "Classic"},
    "229": {"title": "The Rebel", "author": "Albert Camus", "genre": "Philosophy"},
    "230": {"title": "The Fall", "author": "Albert Camus", "genre": "Classic"},
    "231": {"title": "Nausea", "author": "Jean-Paul Sartre", "genre": "Philosophy"},
    "232": {"title": "No Exit", "author": "Jean-Paul Sartre", "genre": "Philosophy"},
    "233": {"title": "Existentialism is a Humanism", "author": "Jean-Paul Sartre", "genre": "Philosophy"},
    "234": {"title": "The Second Sex", "author": "Simone de Beauvoir", "genre": "Philosophy"},
    "235": {"title": "The Ethics of Ambiguity", "author": "Simone de Beauvoir", "genre": "Philosophy"},
    "236": {"title": "The Mandarins", "author": "Simone de Beauvoir", "genre": "Fiction"},
    "237": {"title": "All Men Are Mortal", "author": "Simone de Beauvoir", "genre": "Fiction"},
    "238": {"title": "The Woman Destroyed", "author": "Simone de Beauvoir", "genre": "Fiction"},
    "239": {"title": "She Came to Stay", "author": "Simone de Beauvoir", "genre": "Fiction"},
    "240": {"title": "Memoirs of a Dutiful Daughter", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "241": {"title": "The Prime of Life", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "242": {"title": "Force of Circumstance", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "243": {"title": "All Said and Done", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "244": {"title": "Letters to Sartre", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "245": {"title": "Farewell to Sartre", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "246": {"title": "After the War", "author": "Simone de Beauvoir", "genre": "Memoir"},
    "247": {"title": "Simone de Beauvoir and Jean-Paul Sartre", "author": "Kate Kirkpatrick", "genre": "Biography"},
    "248": {"title": "Becoming Beauvoir", "author": "Kate Kirkpatrick", "genre": "Biography"},
    "249": {"title": "The Biography of Simone de Beauvoir", "author": "Deirdre Bair", "genre": "Biography"},
    "250": {"title": "Feminist Writings", "author": "Simone de Beauvoir", "genre": "Philosophy"},
    "251": {"title": "A Vindication of the Rights of Woman", "author": "Mary Wollstonecraft", "genre": "Philosophy"},
    "252": {"title": "The Second Sex", "author": "Simone de Beauvoir", "genre": "Philosophy"},
    "253": {"title": "Gender Trouble", "author": "Judith Butler", "genre": "Philosophy"},
    "254": {"title": "The Feminine Mystique", "author": "Betty Friedan", "genre": "Philosophy"},
    "255": {"title": "Women, Race, and Class", "author": "Angela Davis", "genre": "Philosophy"},
    "256": {"title": "Sister Outsider", "author": "Audre Lorde", "genre": "Philosophy"},
    "257": {"title": "The Color Purple", "author": "Alice Walker", "genre": "Fiction"},
    "258": {"title": "Beloved", "author": "Toni Morrison", "genre": "Fiction"},
    "259": {"title": "Song of Solomon", "author": "Toni Morrison", "genre": "Fiction"},
    "260": {"title": "Sula", "author": "Toni Morrison", "genre": "Fiction"},
    "261": {"title": "The Bluest Eye", "author": "Toni Morrison", "genre": "Fiction"},
    "262": {"title": "Home", "author": "Toni Morrison", "genre": "Fiction"},
    "263": {"title": "Paradise", "author": "Toni Morrison", "genre": "Fiction"},
    "264": {"title": "God Help the Child", "author": "Toni Morrison", "genre": "Fiction"},
    "265": {"title": "Love", "author": "Toni Morrison", "genre": "Fiction"},
    "266": {"title": "A Mercy", "author": "Toni Morrison", "genre": "Fiction"},
    "267": {"title": "Tar Baby", "author": "Toni Morrison", "genre": "Fiction"},
    "268": {"title": "The Paris Review Interviews, Vol. 1", "author": "The Paris Review", "genre": "Non-Fiction"},
    "269": {"title": "The Paris Review Interviews, Vol. 2", "author": "The Paris Review", "genre": "Non-Fiction"},
    "270": {"title": "The Paris Review Interviews, Vol. 3", "author": "The Paris Review", "genre": "Non-Fiction"},
    "271": {"title": "The Paris Review Interviews, Vol. 4", "author": "The Paris Review", "genre": "Non-Fiction"},
    "272": {"title": "The Art of Fiction", "author": "David Lodge", "genre": "Non-Fiction"},
    "273": {"title": "How Fiction Works", "author": "James Wood", "genre": "Non-Fiction"},
    "274": {"title": "The Elements of Style", "author": "William Strunk Jr. & E.B. White", "genre": "Non-Fiction"},
    "275": {"title": "On Writing", "author": "Stephen King", "genre": "Non-Fiction"},
    "276": {"title": "Bird by Bird", "author": "Anne Lamott", "genre": "Non-Fiction"},
    "277": {"title": "Writing Down the Bones", "author": "Natalie Goldberg", "genre": "Non-Fiction"},
    "278": {"title": "The Artist's Way", "author": "Julia Cameron", "genre": "Non-Fiction"},
    "279": {"title": "Zen in the Art of Writing", "author": "Ray Bradbury", "genre": "Non-Fiction"},
    "280": {"title": "The Writing Life", "author": "Annie Dillard", "genre": "Non-Fiction"},
    "281": {"title": "Letters to a Young Poet", "author": "Rainer Maria Rilke", "genre": "Non-Fiction"},
    "282": {"title": "The War of Art", "author": "Steven Pressfield", "genre": "Non-Fiction"},
    "283": {"title": "On Writing Well", "author": "William Zinsser", "genre": "Non-Fiction"},
    "284": {"title": "The Hero with a Thousand Faces", "author": "Joseph Campbell", "genre": "Non-Fiction"},
    "285": {"title": "The Writer's Journey", "author": "Christopher Vogler", "genre": "Non-Fiction"},
}

def display_books():
    print("Available Books:")
    for key, value in books.items():
        print(f"{key}. {value['title']} by {value['author']} ({value['genre']})")

def get_recommendation(genre):
    print(f"Recommendations for {genre} books:")
    for key, value in books.items():
        if value['genre'] == genre:
            print(f"{key}. {value['title']} by {value['author']}")

def main():
    while True:
        print("\nBook Recommendation App")
        print("1. Display all books")
        print("2. Get recommendations by genre")
        print("3. Exit")
        choice = input("Enter your choice: ")

        if choice == "1":
            display_books()
        elif choice == "2":
            genre = input("Enter the genre (e.g., Classic, Dystopian, Romance, etc.): ")
            get_recommendation(genre.capitalize())
        elif choice == "3":
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()
